language: c++

compiler:
 - clang
 - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcppunit-dev
  - sudo apt-get install -y libjsoncpp-dev

# before build script, run autoreconf
before_script: mkdir -p m4 && ./autogen.sh
script: ./configure --disable-shared && make && make check
