g++ main_testVCLemu.cpp testVCLemu.cpp -I include -L lib -lcppunit -o main_testVCLemu
g++ main_testExceptions.cpp testExceptions.cpp -I include -L lib -lcppunit -o main_testExceptions
g++ main_testScalars.cpp testScalars.cpp -I include -L lib -lcppunit -o main_testScalars
g++ main_testVectors.cpp testVectors.cpp -I include -L lib -lcppunit -o main_testVectors
g++ main_testGeometry.cpp testGeometry.cpp -I include -L lib -lcppunit -o main_testGeometry
g++ main_testStrings.cpp testStrings.cpp -I include -L lib -lcppunit -o main_testStrings
g++ main_testStrPR.cpp testStrPR.cpp -I include -L lib -lcppunit -o main_testStrPR
g++ main_testTextFile.cpp testTextFile.cpp -I include -L lib -lcppunit -o main_testTextFile
g++ main_testSlideArray.cpp testSlideArray.cpp -I include -L lib -lcppunit -o main_testSlideArray
g++ main_testPointersSlideArray.cpp testPointersSlideArray.cpp -I include -L lib -lcppunit -o main_testPointersSlideArray
g++ main_testItemsList.cpp testItemsList.cpp -I include -L lib -lcppunit -o main_testItemsList
g++ main_testPointersList.cpp testPointersList.cpp -I include -L lib -lcppunit -o main_testPointersList
g++ main_testVector.cpp testVector.cpp -I include -L lib -lcppunit -o main_testVector
g++ main_testQuantificator.cpp testQuantificator.cpp -I include -L lib -lcppunit -o main_testQuantificator
g++ main_testFunction.cpp testFunction.cpp -I include -L lib -lcppunit -o main_testFunction
g++ main_testMotionFunction.cpp testMotionFunction.cpp -I include -L lib -lcppunit -o main_testMotionFunction
g++ main_testSquareFunction.cpp testSquareFunction.cpp -I include -L lib -lcppunit -o main_testSquareFunction
g++ main_testRampFunction.cpp testRampFunction.cpp -I include -L lib -lcppunit -o main_testRampFunction
g++ main_testComposedMotionFunction.cpp testComposedMotionFunction.cpp -I include -L lib -lcppunit -o main_testComposedMotionFunction
g++ main_testFigure.cpp testFigure.cpp -I include -L lib -lcppunit -o main_testFigure
g++ main_testContourFigureList.cpp testContourFigureList.cpp -I include -L lib -lcppunit -o main_testContourFigureList
g++ main_testBarrier.cpp testBarrier.cpp -I include -L lib -lcppunit -o main_testBarrier
g++ main_testExclusionArea.cpp testExclusionArea.cpp -I include -L lib -lcppunit -o main_testExclusionArea
g++ main_testExclusionAreaList.cpp testExclusionAreaList.cpp -I include -L lib -lcppunit -o main_testExclusionAreaList
g++ main_testInstruction.cpp testInstruction.cpp -I include -L lib -lcppunit -o main_testInstruction
g++ main_testMessageInstruction.cpp testMessageInstruction.cpp -I include -L lib -lcppunit -o main_testMessageInstruction
g++ main_testPairPositionAngles.cpp testPairPositionAngles.cpp -I include -L lib -lcppunit -o main_testPairPositionAngles
g++ main_testMotionProgram.cpp testMotionProgram.cpp -I include -L lib -lcppunit -o main_testMotionProgram
g++ main_testArm.cpp testArm.cpp -I include -L lib -lcppunit -o main_testArm
g++ main_testCilinder.cpp testCilinder.cpp -I include -L lib -lcppunit -o main_testCilinder
g++ main_testActuator.cpp testActuator.cpp -I include -L lib -lcppunit -o main_testActuator
g++ main_testRoboticPositioner.cpp testRoboticPositioner.cpp -I include -L lib -lcppunit -o main_testRoboticPositioner
g++ main_testRoboticPositioner1List.cpp testRoboticPositionerList1.cpp -I include -L lib -lcppunit -o main_testRoboticPositioner1List
g++ main_testRoboticPositioner2List.cpp testRoboticPositionerList2.cpp -I include -L lib -lcppunit -o main_testRoboticPositioner2List
g++ main_testRoboticPositioner3List.cpp testRoboticPositionerList3.cpp -I include -L lib -lcppunit -o main_testRoboticPositioner3List
g++ main_testFiberMOSModel.cpp testFiberMOSModel.cpp -I include -L lib -lcppunit -o main_testFiberMOSModel
g++ main_testFiberConnectionModel.cpp testFiberConnectionModel.cpp -I include -L lib -lcppunit -o main_testFiberConnectionModel
g++ main_testSkyPoint.cpp testSkyPoint.cpp -I include -L lib -lcppunit -o main_testSkyPoint
g++ main_testProjectionPoint.cpp testProjectionPoint.cpp -I include -L lib -lcppunit -o main_testProjectionPoint
g++ main_testTile.cpp testTile.cpp -I include -L lib -lcppunit -o main_testTile
g++ main_testTelescopeProjectionModel.cpp testTelescopeProjectionModel.cpp -I include -L lib -lcppunit -o main_testTelescopeProjectionModel
g++ main_testAllocation.cpp testAllocation.cpp -I include -L lib -lcppunit -o main_testAllocation
g++ main_testAllocationList.cpp testAllocationList.cpp -I include -L lib -lcppunit -o main_testAllocationList
#g++ main_testMotionProgramValidator.cpp testMotionProgramValidator.cpp -I include -L lib -lcppunit -o main_testMotionProgramValidator
g++ main_testMotionProgramGenerator.cpp testMotionProgramGenerator.cpp -I include -L lib -lcppunit -o main_testMotionProgramGenerator
#g++ main_testPositionerCenter.cpp testPositionerCenter.cpp -I include -L lib -lcppunit -o main_testPositionerCenter
#g++ main_testFileMethods.cpp testFileMethods.cpp -I include -L lib -lcppunit -o main_testFileMethods
g++ main_testFMOSATable.cpp testFMOSATable.cpp -I include -L lib -lcppunit -o main_testFMOSATable
g++ main_testOutputs.cpp testOutputs.cpp -I include -L lib -lcppunit -o main_testOutputs

